In [19]:
import torch
import numpy as np

In [21]:
np.random.rand(4,2)

array([[0.11765422, 0.20154918],
       [0.15164076, 0.47862586],
       [0.58398265, 0.92327006],
       [0.42489727, 0.59051729]])

In [16]:
def function01(tensor: torch.Tensor, count_over: str) -> torch.Tensor:
    if count_over == 'columns':
        return torch.mean(tensor, dim=0)
    if count_over == 'rows':
        return torch.mean(tensor, dim=1)
    raise ValueError("count_over sholud be either 'columns' or 'rows'")

In [13]:
a = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float16)

In [18]:
function01(a, 'rows')

tensor([2., 5.], dtype=torch.float16)

In [9]:
a.dtype?

Type:        dtype
String form: torch.int64
File:        c:\users\krot\anaconda3\envs\kc_ml\lib\site-packages\torch\__init__.py
Docstring:   <no docstring>

In [26]:
import torch 

def function02(ds: torch.Tensor) -> torch.Tensor:
    return torch.rand(ds.shape[1], requires_grad=True)

In [35]:
(function02(a).unsqueeze(0) - function02(a).unsqueeze(0))**2

tensor([[0.0084, 0.2621, 0.0047]], grad_fn=<PowBackward0>)

In [46]:
import torch

def function03(X: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    w = torch.rand(X.shape[1], requires_grad=True)

    for i in range(1000):
        pred = X @ w
        loss = torch.mean((y - pred) ** 2)

        if loss < 1:
            break
        else:
            loss.backward()
            with torch.no_grad():
                w -= w.grad * 1e-2
            w.grad.zero_()

    return w


In [47]:
n_features = 2         # Размерность указана для примера, не нужно использовать её в коде
n_objects = 300

w_true = torch.randn(n_features)
X = (torch.rand(n_objects, n_features) - 0.5) * 5
Y = X @ w_true + torch.randn(n_objects) / 2

In [110]:
from tqdm import tqdm
w = torch.rand(X.shape[1], requires_grad=True)

for i in range(1000):
    pred = X @ w
    loss = torch.mean((Y - pred) ** 2)

    if loss < 1:
        break
    else:
        loss.backward()
        with torch.no_grad():
            w = w - w.grad * 1e-2
        w.requires_grad = True
        w.grad.zero_()

AttributeError: 'NoneType' object has no attribute 'zero_'

In [120]:
import torch

def function04(X: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    layer = torch.nn.Linear(in_features=X.shape[1], out_features=1)

    for i in range(1000):
        pred = layer(X).ravel()
        loss = torch.mean((y - pred) ** 2)

        if loss < 0.3:
            break
        else:
            loss.backward()
            with torch.no_grad():
                layer.weight -= layer.weight.grad * 1e-2
                layer.bias -= layer.bias.grad * 1e-2
            layer.zero_grad()

    return layer


In [121]:
function04(X, Y)

  6%|▌         | 55/1000 [00:00<00:00, 2296.88it/s]


Linear(in_features=2, out_features=1, bias=True)