In [1]:
# pip install psycopg2 если библиотека не установлена
import psycopg2

In [2]:
database="startml",
user="robot-startml-ro",
password="pheiph0hahj1Vaif",
host="postgres.lab.karpov.courses",
port=6432

In [3]:
import pandas as pd

df = pd.read_sql(
    """SELECT * FROM "feed_action" LIMIT 10 """,
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

df.head()

ImportError: Using URI string without sqlalchemy installed.

# Из курса матана для DS

In [19]:
# спектральное разложение
import numpy as np

A = np.array([
    [1,3,4],
    [3,3,1],
    [4,1,2]
])

values, vectors = np.linalg.eigh(A)
# перевод собственных значений в диагональную матрицу
# спектральное разложение => A = V * L * V**-1
values_m = np.diag(values)

new_A = np.dot(vectors, np.dot(values_m, np.linalg.inv(vectors)))

values, vectors, new_A

(array([-3.02069926,  1.66527771,  7.35542155]),
 array([[ 0.77532334,  0.1440438 , -0.61491877],
        [-0.2934401 , -0.78000906, -0.55270134],
        [-0.55925542,  0.60896408, -0.562491  ]]),
 array([[1., 3., 4.],
        [3., 3., 1.],
        [4., 1., 2.]]))

In [27]:
# сингулярное разложение
B = np.array([
    [1,3,8],
    [4,2,0],
    [7,1,9]
])

B_BT = B.dot(B.T)
BT_B = np.dot(B.T, B)

sigma, U = np.linalg.eigh(B_BT)
_, V = np.linalg.eigh(BT_B)

sigma_sqrt = np.diag(np.sqrt(sigma))

new_B = np.dot(U, np.dot(sigma_sqrt, V.T))
new_B

array([[ 6.67070123,  2.5849791 ,  4.77698944],
       [-1.80194323,  2.42462609,  3.29760351],
       [ 4.27255727,  1.19961301, 10.55017455]])